/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as adnodeAdManagerSol from "./AdnodeAdManager.sol";
export type { adnodeAdManagerSol };
export type { AdSlotNFT } from "./AdSlotNFT";
